In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("UK-HPI-full-file-2026-04.csv")
df.shape
df.head()
df.dtypes

Date                       object
RegionName                 object
AreaCode                   object
AveragePrice                int64
Index                     float64
IndexSA                   float64
1m%Change                 float64
12m%Change                float64
AveragePriceSA            float64
SalesVolume               float64
DetachedPrice             float64
DetachedIndex             float64
Detached1m%Change         float64
Detached12m%Change        float64
SemiDetachedPrice         float64
SemiDetachedIndex         float64
SemiDetached1m%Change     float64
SemiDetached12m%Change    float64
TerracedPrice             float64
TerracedIndex             float64
Terraced1m%Change         float64
Terraced12m%Change        float64
FlatPrice                 float64
FlatIndex                 float64
Flat1m%Change             float64
Flat12m%Change            float64
CashPrice                 float64
CashIndex                 float64
Cash1m%Change             float64
Cash12m%Change            float64
CashSalesVolume           float64
MortgagePrice             float64
MortgageIndex             float64
Mortgage1m%Change         float64
Mortgage12m%Change        float64
MortgageSalesVolume       float64
FTBPrice                  float64
FTBIndex                  float64
FTB1m%Change              float64
FTB12m%Change             float64
FOOPrice                  float64
FOOIndex                  float64
FOO1m%Change              float64
FOO12m%Change             float64
NewPrice                  float64
NewIndex                  float64
New1m%Change              float64
New12m%Change             float64
NewSalesVolume            float64
OldPrice                  float64
OldIndex                  float64
Old1m%Change              float64
Old12m%Change             float64
OldSalesVolume            float64
dtype: object

In [6]:
df['Date']=pd.to_datetime(df['Date'])
df['RegionName']=df['RegionName'].astype('category')
df['AreaCode']=df['AreaCode'].astype('category')

In [7]:
print(df['Date'].min(), df['Date'].max())
print(df["RegionName"].nunique(),"unique regions")
df['RegionName'].unique

1968-01-04 00:00:00 2026-01-04 00:00:00
405 unique regions

<bound method Series.unique of 0                    Aberdeenshire
1                    Aberdeenshire
2                    Aberdeenshire
3                    Aberdeenshire
4                    Aberdeenshire
                    ...
150700    Yorkshire and The Humber
150701    Yorkshire and The Humber
150702    Yorkshire and The Humber
150703    Yorkshire and The Humber
150704    Yorkshire and The Humber
Name: RegionName, Length: 150705, dtype: category
Categories (405, object): ['Aberdeenshire', 'Adur', 'Amber Valley', 'Angus', ..., 'Wyre', 'Wyre Forest', 'York', 'Yorkshire and The Humber']>

In [9]:
df.duplicated(subset=['Date','RegionName']).sum()

np.int64(0)

In [12]:
missing_pct=(df.isna().mean() * 100).sort_values(ascending=False)
missing_pct[missing_pct>0]

IndexSA                   96.480541
AveragePriceSA            96.480541
Mortgage12m%Change        58.382270
FOO12m%Change             58.382270
Cash12m%Change            58.382270
FTB12m%Change             58.119505
CashSalesVolume           55.783153
MortgageSalesVolume       55.782489
Cash1m%Change             55.521051
Mortgage1m%Change         55.521051
FOO1m%Change              55.521051
FOOIndex                  55.260940
MortgageIndex             55.260940
CashPrice                 55.260940
MortgagePrice             55.260940
CashIndex                 55.260940
FOOPrice                  55.260940
FTB1m%Change              55.258286
FTBPrice                  54.998175
FTBIndex                  54.998175
New12m%Change              8.090641
Old12m%Change              7.955277
SemiDetached12m%Change     7.673933
Detached12m%Change         7.673933
Terraced12m%Change         7.608241
Flat12m%Change             7.432401
NewSalesVolume             7.339504
New1m%Change               5.216151
Old1m%Change               5.080787
NewIndex                   4.953386
NewPrice                   4.953386
OldSalesVolume             4.825985
OldIndex                   4.818022
OldPrice                   4.818022
Detached1m%Change          4.806742
SemiDetached1m%Change      4.806742
Terraced1m%Change          4.733751
Flat1m%Change              4.557911
DetachedIndex              4.544640
SemiDetachedPrice          4.544640
SemiDetachedIndex          4.544640
DetachedPrice              4.544640
TerracedIndex              4.470986
TerracedPrice              4.470986
FlatPrice                  4.295146
FlatIndex                  4.295146
12m%Change                 3.224843
SalesVolume                2.964069
1m%Change                  0.300587
dtype: float64

In [ ]:
sa_by_region= df.groupby('RegionName')['IndexSA'].apply(lambda s: s.notna().mean())

C:\Users\Misbha\AppData\Local\Temp\ipykernel_13484\1374958862.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sa_by_region= df.groupby('RegionName')['IndexSA'].apply(lambda s: s.notna().mean())

(390,)

In [18]:
sa_by_region.sort_values(ascending=False).head(15)

RegionName
Great Britain               1.000000
England and Wales           1.000000
North West                  1.000000
East of England             0.919315
North East                  0.919315
South East                  0.919315
London                      0.539455
East Midlands               0.539455
Yorkshire and The Humber    0.539455
England                     0.539455
West Midlands Region        0.539455
South West                  0.539455
Wales                       0.539455
Scotland                    0.384505
United Kingdom              0.367288
Name: IndexSA, dtype: float64

In [21]:
gb_data=df[df['RegionName']=='Great Britain']
gb_data[gb_data['IndexSA'].notna()]['Date'].min()

Timestamp('2004-01-01 00:00:00')

In [20]:
scotland_data = df[df['RegionName'] == 'Scotland']
scotland_data[scotland_data['IndexSA'].notna()]['Date'].min()

Timestamp('2004-01-01 00:00:00')

In [23]:
df_check = pd.read_csv("UK-HPI-full-file-2026-04.csv", usecols=['Date'])
df_check['Date'].head(10)

0    01/01/2004
1    01/02/2004
2    01/03/2004
3    01/04/2004
4    01/05/2004
5    01/06/2004
6    01/07/2004
7    01/08/2004
8    01/09/2004
9    01/10/2004
Name: Date, dtype: object

In [24]:
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)

In [25]:
df['Date'].head(10)

0   2004-01-01
1   2004-01-02
2   2004-01-03
3   2004-01-04
4   2004-01-05
5   2004-01-06
6   2004-01-07
7   2004-01-08
8   2004-01-09
9   2004-01-10
Name: Date, dtype: datetime64[ns]

In [27]:
df = pd.read_csv("UK-HPI-full-file-2026-04.csv")   # reload everything fresh
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)   # convert correctly this time
df['Date'].head(10)

0   2004-01-01
1   2004-02-01
2   2004-03-01
3   2004-04-01
4   2004-05-01
5   2004-06-01
6   2004-07-01
7   2004-08-01
8   2004-09-01
9   2004-10-01
Name: Date, dtype: datetime64[ns]

In [28]:
df['RegionName'] = df['RegionName'].astype('category')
df['AreaCode'] = df['AreaCode'].astype('category')

In [29]:
df.groupby(df['Date'].dt.year)['CashPrice'].apply(lambda s: s.notna().mean())

Date
1968    0.000000
1969    0.000000
1970    0.000000
1971    0.000000
1972    0.000000
1973    0.000000
1974    0.000000
1975    0.000000
1976    0.000000
1977    0.000000
1978    0.000000
1979    0.000000
1980    0.000000
1981    0.000000
1982    0.000000
1983    0.000000
1984    0.000000
1985    0.000000
1986    0.000000
1987    0.000000
1988    0.000000
1989    0.000000
1990    0.000000
1991    0.000000
1992    0.000000
1993    0.000000
1994    0.000000
1995    0.000000
1996    0.000000
1997    0.000000
1998    0.000000
1999    0.000000
2000    0.000000
2001    0.000000
2002    0.000000
2003    0.000000
2004    0.000000
2005    0.000000
2006    0.000000
2007    0.000000
2008    0.000000
2009    0.000000
2010    0.000000
2011    0.000000
2012    0.967901
2013    0.967901
2014    0.967901
2015    0.967901
2016    0.967901
2017    0.967901
2018    0.967901
2019    0.967901
2020    0.967901
2021    0.967901
2022    0.967901
2023    0.967901
2024    0.967901
2025    0.967901
2026    0.967901
Name: CashPrice, dtype: float64

In [30]:
cash_by_year = df.groupby(df['Date'].dt.year)['CashPrice'].apply(lambda s: s.notna().mean())
cash_by_year[cash_by_year > 0].index.min()

np.int32(2012)

In [31]:
ftb_by_year = df.groupby(df['Date'].dt.year)['FTBPrice'].apply(lambda s: s.notna().mean())
ftb_by_year[ftb_by_year > 0].index.min()

np.int32(2011)

In [32]:
detached_by_year = df.groupby(df['Date'].dt.year)['DetachedPrice'].apply(lambda s: s.notna().mean())
detached_by_year[detached_by_year > 0].index.min()

np.int32(1995)

In [33]:
new_by_year = df.groupby(df['Date'].dt.year)['NewPrice'].apply(lambda s: s.notna().mean())
new_by_year[new_by_year > 0].index.min()

np.int32(1995)

In [34]:
# --- Flag structural data availability (don't delete/impute — just label reality) ---

df['HasPropertyTypeBreakdown'] = df['Date'].dt.year >= 1995   # Detached/SemiDetached/Terraced/Flat, New/Old
df['HasBuyerTypeBreakdown']    = df['Date'].dt.year >= 2011   # FTB/FOO
df['HasFundingBreakdown']      = df['Date'].dt.year >= 2012   # Cash/Mortgage

national_regional = sa_by_region[sa_by_region > 0].index.tolist()
df['HasSeasonalAdjustment']    = df['RegionName'].isin(national_regional) & (df['Date'].dt.year >= 2004)

In [35]:
# Any row that claims to have the breakdown but is actually still NaN? Should be 0.
(df[df['HasPropertyTypeBreakdown']]['DetachedPrice'].isna()).sum()

np.int64(3540)

In [36]:
gap_rows = df[df['HasPropertyTypeBreakdown'] & df['DetachedPrice'].isna()]
gap_rows['RegionName'].value_counts().head(15)

RegionName
City of London                         376
Belfast                                256
Lisburn and Castlereagh                256
Derry City and Strabane                256
Ards and North Down                    256
Antrim and Newtownabbey                256
Fermanagh and Omagh                    256
Causeway Coast and Glens               256
Mid Ulster                             256
Mid and East Antrim                    256
Newry Mourne and Down                  256
Armagh City Banbridge and Craigavon    256
Northern Ireland                       120
United Kingdom                         120
Scotland                               108
Name: count, dtype: int64

In [37]:
gap_rows['Date'].dt.year.value_counts().sort_index()

Date
1995     48
1996     48
1997     48
1998     48
1999     48
2000     48
2001     48
2002     48
2003     48
2004     36
2005    144
2006    144
2007    144
2008    144
2009    144
2010    144
2011    144
2012    144
2013    144
2014    144
2015    144
2016    144
2017    144
2018    144
2019    144
2020    144
2021    144
2022    144
2023    144
2024    144
2025    144
2026     48
Name: count, dtype: int64

In [38]:
ni_regions = ['Belfast', 'Lisburn and Castlereagh', 'Derry City and Strabane',
              'Ards and North Down', 'Antrim and Newtownabbey', 'Fermanagh and Omagh',
              'Causeway Coast and Glens', 'Mid Ulster', 'Mid and East Antrim',
              'Newry Mourne and Down', 'Armagh City Banbridge and Craigavon',
              'Northern Ireland']

ni_by_year = df[df['RegionName'].isin(ni_regions)].groupby(df['Date'].dt.year)['DetachedPrice'].apply(lambda s: s.notna().mean())
ni_by_year[ni_by_year > 0].index.min()

np.int32(2005)

In [39]:
scotland_by_year = df[df['RegionName'] == 'Scotland'].groupby(df['Date'].dt.year)['DetachedPrice'].apply(lambda s: s.notna().mean())
scotland_by_year[scotland_by_year > 0].index.min()

np.int32(2004)

In [40]:
def get_property_type_start_year(region):
    if region in ni_regions:
        return 2005
    elif region == 'Scotland':
        return 2004
    else:
        return 1995

df['PropertyTypeStartYear'] = df['RegionName'].apply(get_property_type_start_year)
df['HasPropertyTypeBreakdown'] = df['Date'].dt.year >= df['PropertyTypeStartYear']

In [41]:
(df[df['HasPropertyTypeBreakdown']]['DetachedPrice'].isna()).sum()

np.int64(3312)

In [42]:
df[df['HasPropertyTypeBreakdown'] & df['DetachedPrice'].isna()]['RegionName'].value_counts()

RegionName
City of London                  376
Belfast                         256
Lisburn and Castlereagh         256
Derry City and Strabane         256
Ards and North Down             256
                               ...
Basingstoke and Deane             0
Bassetlaw                         0
Bath and North East Somerset      0
Bedford                           0
Welwyn Hatfield                   0
Name: count, Length: 405, dtype: int64

In [43]:
df[df['RegionName'] == 'Belfast'].groupby(df['Date'].dt.year)['DetachedPrice'].apply(lambda s: s.notna().mean())

Date
2005    0.0
2006    0.0
2007    0.0
2008    0.0
2009    0.0
2010    0.0
2011    0.0
2012    0.0
2013    0.0
2014    0.0
2015    0.0
2016    0.0
2017    0.0
2018    0.0
2019    0.0
2020    0.0
2021    0.0
2022    0.0
2023    0.0
2024    0.0
2025    0.0
2026    0.0
Name: DetachedPrice, dtype: float64

In [44]:
ni_districts = ['Belfast', 'Lisburn and Castlereagh', 'Derry City and Strabane',
                 'Ards and North Down', 'Antrim and Newtownabbey', 'Fermanagh and Omagh',
                 'Causeway Coast and Glens', 'Mid Ulster', 'Mid and East Antrim',
                 'Newry Mourne and Down', 'Armagh City Banbridge and Craigavon']

df[df['RegionName'].isin(ni_districts)].groupby('RegionName')['DetachedPrice'].apply(lambda s: s.notna().mean())

C:\Users\Misbha\AppData\Local\Temp\ipykernel_13484\3869917156.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[df['RegionName'].isin(ni_districts)].groupby('RegionName')['DetachedPrice'].apply(lambda s: s.notna().mean())

RegionName
Aberdeenshire               NaN
Adur                        NaN
Amber Valley                NaN
Angus                       NaN
Antrim and Newtownabbey     0.0
                           ...
Wychavon                    NaN
Wyre                        NaN
Wyre Forest                 NaN
York                        NaN
Yorkshire and The Humber    NaN
Name: DetachedPrice, Length: 405, dtype: float64

In [45]:
ni_districts = ['Belfast', 'Lisburn and Castlereagh', 'Derry City and Strabane',
                 'Ards and North Down', 'Antrim and Newtownabbey', 'Fermanagh and Omagh',
                 'Causeway Coast and Glens', 'Mid Ulster', 'Mid and East Antrim',
                 'Newry Mourne and Down', 'Armagh City Banbridge and Craigavon']

ni_check = df[df['RegionName'].isin(ni_districts)]
ni_check.groupby('RegionName')['DetachedPrice'].apply(lambda s: s.notna().mean())

C:\Users\Misbha\AppData\Local\Temp\ipykernel_13484\219142883.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ni_check.groupby('RegionName')['DetachedPrice'].apply(lambda s: s.notna().mean())

RegionName
Aberdeenshire               NaN
Adur                        NaN
Amber Valley                NaN
Angus                       NaN
Antrim and Newtownabbey     0.0
                           ...
Wychavon                    NaN
Wyre                        NaN
Wyre Forest                 NaN
York                        NaN
Yorkshire and The Humber    NaN
Name: DetachedPrice, Length: 405, dtype: float64

In [46]:
ni_districts = ['Belfast', 'Lisburn and Castlereagh', 'Derry City and Strabane',
                 'Ards and North Down', 'Antrim and Newtownabbey', 'Fermanagh and Omagh',
                 'Causeway Coast and Glens', 'Mid Ulster', 'Mid and East Antrim',
                 'Newry Mourne and Down', 'Armagh City Banbridge and Craigavon']

ni_check = df[df['RegionName'].isin(ni_districts)]
ni_check.groupby('RegionName')['DetachedPrice'].apply(lambda s: s.notna().mean())

C:\Users\Misbha\AppData\Local\Temp\ipykernel_13484\219142883.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ni_check.groupby('RegionName')['DetachedPrice'].apply(lambda s: s.notna().mean())

RegionName
Aberdeenshire               NaN
Adur                        NaN
Amber Valley                NaN
Angus                       NaN
Antrim and Newtownabbey     0.0
                           ...
Wychavon                    NaN
Wyre                        NaN
Wyre Forest                 NaN
York                        NaN
Yorkshire and The Humber    NaN
Name: DetachedPrice, Length: 405, dtype: float64

In [47]:
ni_check = df[df['RegionName'].isin(ni_districts)]
ni_check.shape

(2816, 59)

In [48]:
ni_check['RegionName'].unique()

['Antrim and Newtownabbey', 'Ards and North Down', 'Armagh City Banbridge and Craigavon', 'Belfast', 'Causeway Coast and Glens', ..., 'Fermanagh and Omagh', 'Lisburn and Castlereagh', 'Mid Ulster', 'Mid and East Antrim', 'Newry Mourne and Down']
Length: 11
Categories (405, object): ['Aberdeenshire', 'Adur', 'Amber Valley', 'Angus', ..., 'Wyre', 'Wyre Forest', 'York', 'Yorkshire and The Humber']

In [49]:
ni_check = df[df['RegionName'].isin(ni_districts)]
ni_check.groupby('RegionName')['DetachedPrice'].apply(lambda s: s.notna().mean())

C:\Users\Misbha\AppData\Local\Temp\ipykernel_13484\19684458.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ni_check.groupby('RegionName')['DetachedPrice'].apply(lambda s: s.notna().mean())

RegionName
Aberdeenshire               NaN
Adur                        NaN
Amber Valley                NaN
Angus                       NaN
Antrim and Newtownabbey     0.0
                           ...
Wychavon                    NaN
Wyre                        NaN
Wyre Forest                 NaN
York                        NaN
Yorkshire and The Humber    NaN
Name: DetachedPrice, Length: 405, dtype: float64

In [50]:
ni_check.groupby('RegionName', observed=True)['DetachedPrice'].apply(lambda s: s.notna().mean())

RegionName
Antrim and Newtownabbey                0.0
Ards and North Down                    0.0
Armagh City Banbridge and Craigavon    0.0
Belfast                                0.0
Causeway Coast and Glens               0.0
Derry City and Strabane                0.0
Fermanagh and Omagh                    0.0
Lisburn and Castlereagh                0.0
Mid Ulster                             0.0
Mid and East Antrim                    0.0
Newry Mourne and Down                  0.0
Name: DetachedPrice, dtype: float64

In [51]:
ni_districts = ['Belfast', 'Lisburn and Castlereagh', 'Derry City and Strabane',
                 'Ards and North Down', 'Antrim and Newtownabbey', 'Fermanagh and Omagh',
                 'Causeway Coast and Glens', 'Mid Ulster', 'Mid and East Antrim',
                 'Newry Mourne and Down', 'Armagh City Banbridge and Craigavon']

def has_property_breakdown(row):
    if row['RegionName'] in ni_districts:
        return False   # never published at this geography level
    elif row['RegionName'] == 'Scotland':
        return row['Date'].year >= 2004
    elif row['RegionName'] == 'Northern Ireland':
        return row['Date'].year >= 2005
    else:
        return row['Date'].year >= 1995

df['HasPropertyTypeBreakdown'] = df.apply(has_property_breakdown, axis=1)

In [52]:
(df[df['HasPropertyTypeBreakdown']]['DetachedPrice'].isna()).sum()

np.int64(496)

In [53]:
remaining_gaps = df[df['HasPropertyTypeBreakdown'] & df['DetachedPrice'].isna()]
remaining_gaps.groupby('RegionName', observed=True).size()

RegionName
City of London    376
United Kingdom    120
dtype: int64

In [54]:
uk_check = df[df['RegionName'] == 'United Kingdom']
uk_check.groupby(uk_check['Date'].dt.year, observed=True)['DetachedPrice'].apply(lambda s: s.notna().mean())

Date
1968    0.0
1969    0.0
1970    0.0
1971    0.0
1972    0.0
1973    0.0
1974    0.0
1975    0.0
1976    0.0
1977    0.0
1978    0.0
1979    0.0
1980    0.0
1981    0.0
1982    0.0
1983    0.0
1984    0.0
1985    0.0
1986    0.0
1987    0.0
1988    0.0
1989    0.0
1990    0.0
1991    0.0
1992    0.0
1993    0.0
1994    0.0
1995    0.0
1996    0.0
1997    0.0
1998    0.0
1999    0.0
2000    0.0
2001    0.0
2002    0.0
2003    0.0
2004    0.0
2005    1.0
2006    1.0
2007    1.0
2008    1.0
2009    1.0
2010    1.0
2011    1.0
2012    1.0
2013    1.0
2014    1.0
2015    1.0
2016    1.0
2017    1.0
2018    1.0
2019    1.0
2020    1.0
2021    1.0
2022    1.0
2023    1.0
2024    1.0
2025    1.0
2026    1.0
Name: DetachedPrice, dtype: float64

In [55]:
ni_districts = ['Belfast', 'Lisburn and Castlereagh', 'Derry City and Strabane',
                 'Ards and North Down', 'Antrim and Newtownabbey', 'Fermanagh and Omagh',
                 'Causeway Coast and Glens', 'Mid Ulster', 'Mid and East Antrim',
                 'Newry Mourne and Down', 'Armagh City Banbridge and Craigavon']

def has_property_breakdown(row):
    if row['RegionName'] in ni_districts or row['RegionName'] == 'City of London':
        return False   # never published — too few sales at this geography level
    elif row['RegionName'] == 'Scotland':
        return row['Date'].year >= 2004
    elif row['RegionName'] in ('Northern Ireland', 'United Kingdom'):
        return row['Date'].year >= 2005
    else:
        return row['Date'].year >= 1995

df['HasPropertyTypeBreakdown'] = df.apply(has_property_breakdown, axis=1)

In [56]:
(df[df['HasPropertyTypeBreakdown']]['DetachedPrice'].isna()).sum()

np.int64(0)

In [57]:
df['HasFundingBreakdown'] = df['Date'].dt.year >= 2012
df['HasBuyerTypeBreakdown'] = df['Date'].dt.year >= 2011

print("Funding gap:", (df[df['HasFundingBreakdown']]['CashPrice'].isna()).sum())
print("Buyer gap:", (df[df['HasBuyerTypeBreakdown']]['FTBPrice'].isna()).sum())

Funding gap: 2236
Buyer gap: 6700

In [58]:
national_regional = sa_by_region[sa_by_region > 0].index.tolist()
df['HasSeasonalAdjustment'] = df['RegionName'].isin(national_regional) & (df['Date'].dt.year >= 2004)

(df[df['HasSeasonalAdjustment']]['IndexSA'].isna()).sum()

np.int64(12)

In [59]:
funding_gaps = df[df['HasFundingBreakdown'] & df['CashPrice'].isna()]
funding_gaps.groupby('RegionName', observed=True).size().sort_values(ascending=False).head(15)

RegionName
Antrim and Newtownabbey                172
Ards and North Down                    172
Armagh City Banbridge and Craigavon    172
Belfast                                172
Causeway Coast and Glens               172
Derry City and Strabane                172
Fermanagh and Omagh                    172
Lisburn and Castlereagh                172
Mid Ulster                             172
Mid and East Antrim                    172
Newry Mourne and Down                  172
Northern Ireland                       172
United Kingdom                         172
dtype: int64

In [60]:
buyer_gaps = df[df['HasBuyerTypeBreakdown'] & df['FTBPrice'].isna()]
buyer_gaps.groupby('RegionName', observed=True).size().sort_values(ascending=False).head(15)

RegionName
Fermanagh and Omagh                    184
Causeway Coast and Glens               184
Lisburn and Castlereagh                184
Derry City and Strabane                184
Antrim and Newtownabbey                184
Mid Ulster                             184
Mid and East Antrim                    184
Newry Mourne and Down                  184
Northern Ireland                       184
Ards and North Down                    184
United Kingdom                         184
Armagh City Banbridge and Craigavon    184
Belfast                                184
West Lancashire                         12
West Lindsey                            12
dtype: int64

In [62]:
buyer_gaps = df[df['HasBuyerTypeBreakdown'] & df['FTBPrice'].isna()]
buyer_gaps.groupby('RegionName', observed=True).size().sort_values(ascending=False).head(15)

RegionName
Fermanagh and Omagh                    184
Causeway Coast and Glens               184
Lisburn and Castlereagh                184
Derry City and Strabane                184
Antrim and Newtownabbey                184
Mid Ulster                             184
Mid and East Antrim                    184
Newry Mourne and Down                  184
Northern Ireland                       184
Ards and North Down                    184
United Kingdom                         184
Armagh City Banbridge and Craigavon    184
Belfast                                184
West Lancashire                         12
West Lindsey                            12
dtype: int64

In [63]:
ni_and_uk = ni_districts + ['Northern Ireland', 'United Kingdom']

df['HasFundingBreakdown'] = np.where(
    df['RegionName'].isin(ni_and_uk),
    df['Date'].dt.year >= 2013,   # NI group started a year later than the rest
    df['Date'].dt.year >= 2012
)

df['HasBuyerTypeBreakdown'] = np.where(
    df['RegionName'].isin(ni_and_uk),
    df['Date'].dt.year >= 2012,   # same, one year later for NI group
    df['Date'].dt.year >= 2011
)

In [64]:
print("Funding gap:", (df[df['HasFundingBreakdown']]['CashPrice'].isna()).sum())
print("Buyer gap:", (df[df['HasBuyerTypeBreakdown']]['FTBPrice'].isna()).sum())

Funding gap: 2080
Buyer gap: 6544

In [65]:
ni_group = df[df['RegionName'].isin(ni_and_uk)]

ni_funding_by_year = ni_group.groupby(ni_group['Date'].dt.year, observed=True)['CashPrice'].apply(lambda s: s.notna().mean())
print(ni_funding_by_year[ni_funding_by_year > 0].index.min())

ni_buyer_by_year = ni_group.groupby(ni_group['Date'].dt.year, observed=True)['FTBPrice'].apply(lambda s: s.notna().mean())
print(ni_buyer_by_year[ni_buyer_by_year > 0].index.min())

nan
nan

In [66]:
ni_group.groupby(ni_group['Date'].dt.year, observed=True)['CashPrice'].apply(lambda s: s.notna().mean()).sum()

np.float64(0.0)

In [67]:
col_check = df[df['RegionName'] == 'City of London']
col_check['CashPrice'].notna().mean(), col_check['FTBPrice'].notna().mean()

(np.float64(0.4574468085106383), np.float64(0.4574468085106383))

In [68]:
never_published_group = ni_districts + ['Northern Ireland', 'United Kingdom', 'City of London']

df['HasFundingBreakdown'] = (~df['RegionName'].isin(never_published_group)) & (df['Date'].dt.year >= 2012)
df['HasBuyerTypeBreakdown'] = (~df['RegionName'].isin(never_published_group)) & (df['Date'].dt.year >= 2011)

In [69]:
col_by_year = col_check.groupby(col_check['Date'].dt.year, observed=True)['CashPrice'].apply(lambda s: s.notna().mean())
col_by_year[col_by_year > 0].index.min()

np.int32(2012)

In [70]:
ni_never_published = ni_districts + ['Northern Ireland', 'United Kingdom']

df['HasFundingBreakdown'] = (~df['RegionName'].isin(ni_never_published)) & (df['Date'].dt.year >= 2012)
df['HasBuyerTypeBreakdown'] = (~df['RegionName'].isin(ni_never_published)) & (df['Date'].dt.year >= 2011)

print("Funding gap:", (df[df['HasFundingBreakdown']]['CashPrice'].isna()).sum())
print("Buyer gap:", (df[df['HasBuyerTypeBreakdown']]['FTBPrice'].isna()).sum())

Funding gap: 0
Buyer gap: 4308

In [71]:
buyer_gaps = df[df['HasBuyerTypeBreakdown'] & df['FTBPrice'].isna()]
buyer_gaps.groupby('RegionName', observed=True).size().sort_values(ascending=False).head(15)

RegionName
Adur                            12
Amber Valley                    12
Arun                            12
Ashfield                        12
Ashford                         12
Babergh                         12
Barking and Dagenham            12
Barnet                          12
Barnsley                        12
Basildon                        12
Basingstoke and Deane           12
Bassetlaw                       12
Bath and North East Somerset    12
Bedford                         12
Bexley                          12
dtype: int64

In [72]:
col_buyer_by_year = col_check.groupby(col_check['Date'].dt.year, observed=True)['FTBPrice'].apply(lambda s: s.notna().mean())
col_buyer_by_year[col_buyer_by_year > 0].index.min()

np.int32(2012)

In [73]:
4308 / 12

359.0

In [74]:
gap_years = buyer_gaps.groupby(buyer_gaps['Date'].dt.year).size()
gap_years[gap_years > 0]

Date
2011    4308
dtype: int64

In [75]:
df['HasBuyerTypeBreakdown'] = (~df['RegionName'].isin(ni_never_published)) & (df['Date'].dt.year >= 2012)

print("Buyer gap:", (df[df['HasBuyerTypeBreakdown']]['FTBPrice'].isna()).sum())

Buyer gap: 0

In [76]:
change_gaps = df[df['1m%Change'].isna()]
change_gaps.groupby('RegionName', observed=True).size().sort_values(ascending=False).head(10)

RegionName
Belfast                     3
West Midlands Region        3
Derry City and Strabane     3
Ards and North Down         3
Yorkshire and The Humber    3
Antrim and Newtownabbey     3
Fermanagh and Omagh         3
Lisburn and Castlereagh     3
Causeway Coast and Glens    3
London                      3
dtype: int64

In [77]:
# Any impossible prices?
print("Zero or negative prices:", (df['AveragePrice'] <= 0).sum())

# Any suspiciously extreme month-on-month swings?
extreme_changes = df[df['1m%Change'].abs() > 50]
print("Extreme 1m changes:", len(extreme_changes))
extreme_changes[['Date','RegionName','AveragePrice','1m%Change']].head(10)

Zero or negative prices: 0
Extreme 1m changes: 0

Empty DataFrame
Columns: [Date, RegionName, AveragePrice, 1m%Change]
Index: []

In [78]:
belfast_gaps = df[(df['RegionName'] == 'Belfast') & (df['1m%Change'].isna())]
belfast_gaps[['Date', 'AveragePrice', '1m%Change']]

           Date  AveragePrice  1m%Change
6836 2005-01-01         99462        NaN
6837 2005-02-01         99462        NaN
6838 2005-03-01         99462        NaN

In [80]:
first_three = df.groupby('RegionName', observed=True).head(3)
first_three.groupby('RegionName', observed=True)['AveragePrice'].nunique().value_counts()

AveragePrice
3    377
1     28
Name: count, dtype: int64

In [82]:
df['HasValidChangeCalc'] = ~df['1m%Change'].isna()

In [84]:
df['HasValidChangeCalc'] = ~df['1m%Change'].isna()

# quick check: does this affect much of the dataset overall?
df['HasValidChangeCalc'].value_counts(normalize=True)

HasValidChangeCalc
True     0.996994
False    0.003006
Name: proportion, dtype: float64

In [85]:
# Save your progress so far before moving to feature engineering
df.to_csv("uk_hpi_stage1_cleaned.csv", index=False)
print(df.shape)

(150705, 60)